INSERT INTO TEACHERS (ID, FIRSTNAME, LASTNAME) VALUES (1, 'Sergio', 'Raposo Vargas');
INSERT INTO TEACHERS (ID, FIRSTNAME, LASTNAME) VALUES (2, 'Andres Ricardo', 'Arango Heredia');
INSERT INTO TEACHERS (ID, FIRSTNAME, LASTNAME) VALUES (3, 'Juan José', 'Dominguez Morán');

INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('Angular: Arranca un proyecto desde cero', 'BASICO', 24, 3, 1);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('Angular: Buenas prácticas', 'INTERMEDIO', 24, 2, 1);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('Angular: Conviertete en un Ninja', 'AVANZADO', 24, 1, 1);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('Curso No Activo', 'BASICO', 24, 1, 0);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('Java BASICO', 'BASICO', 8, 1, 1);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('Spring BASICO', 'BASICO', 16, 1, 1);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('MyBatis BASICO', 'BASICO', 16, 1, 1);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('React BASICO', 'BASICO', 24, 1, 1);
INSERT INTO COURSES (TITLE, LEVEL, HOURS, TEACHER_ID, STATE) VALUES('Jersey BASICO', 'BASICO', 24, 1, 1);
