DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS TEACHERS;
DROP TABLE IF EXISTS FILES;

CREATE TABLE TEACHERS (
  ID            	BIGINT(11)      NOT NULL AUTO_INCREMENT,
  FIRSTNAME   		VARCHAR(100)  	NOT NULL,
  LASTNAME			VARCHAR(100)  	NOT NULL,
  PRIMARY KEY (ID),
);

CREATE TABLE FILES (
  ID            	BIGINT(11)      NOT NULL AUTO_INCREMENT,
  FILENAME   		VARCHAR(500)  	NOT NULL,
  CONTENT			BLOB  			NOT NULL,
  PRIMARY KEY (ID),
);

CREATE TABLE COURSES (
  ID            BIGINT(11)      NOT NULL AUTO_INCREMENT,
  TITLE   		VARCHAR(250)  	NOT NULL,
  LEVEL			VARCHAR(80)  	NOT NULL,
  HOURS		   	INT(3)  		NOT NULL,
  TEACHER_ID	BIGINT(11)  	NOT NULL,
  STATE		 	INT(1)  		NOT NULL,
  FILE_ID		 	BIGINT(11)		NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (TITLE)
);
ALTER TABLE COURSES ADD CONSTRAINT FK_COURSES_TEACHERS FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);
ALTER TABLE COURSES ADD CONSTRAINT FK_COURSES_FILES FOREIGN KEY (FILE_ID) REFERENCES FILES (ID);
 


